import type { Metadata } from "next";
import "@/styles/globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import DarkModeToggle from "@/components/DarkModeToogle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jack's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Header />
        {/* <button className="fixed top-12 right-5">
          <p className="w-7 h-7 flex justify-center items-center border border-black rounded-3xl">
            D
          </p>
        </button> */}
        <DarkModeToggle />
        <main className="flex-grow px-4 md:px-10 pt-[60px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
